Updated to latest Bash-Boiler version: 2019.07.11.01.

diff --git a/autopkg-trust-tool b/autopkg-trust-tool
--- a/autopkg-trust-tool
+++ b/autopkg-trust-tool
@@ -1,7 +1,7 @@
 #!/bin/bash
 #### Non-Customizable Header ####
-# BASH_BOILER_VERSION=2019.07.02.01
-# Generated with Bash-Boiler on 07-02-19_16:23:49
+# BASH_BOILER_VERSION=2019.07.11.01
+# Generated with Bash-Boiler on 07-26-19_17:37:05
 # Use updater to update this script:
 # https://github.com/coreyramirezgomez/Bash-Boiler.git
 # Modifying any content between blocks like the following:
@@ -17,15 +17,13 @@ trap catch_exit $?
 
 #### Non-Customizable Global Variables ####
 QUIET=""
-START_TIME=$(date +%s)
+START_TIME="$(date +%s)"
 START_DATE="$(date +%m-%d-%y_%H:%M:%S)"
 VERBOSE=""
-BINARIES_MISSING=()
 #### ####
 
 #### Customizable Variables ####
 ARGS_REQUIRED=1
-BINARIES_OPTIONAL=()
 BINARIES_REQUIRED=( "autopkg" )
 GARBAGE_COLLECTOR=0
 GARBAGE=()
@@ -48,8 +46,9 @@ RECIPE_NAMES=()
 #### Non-Customizable Functions ####
 backup_file()
 {
+	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args ($#): $*"
+	[ $# -lt 1 ] && fail_notice_exit "(${FUNCNAME[0]}) Not enough arguments received." 101
 	case $# in
-		0) fail_notice_exit "(${FUNCNAME[0]}) No Arguments provided." 101 ;;
 		1)
 			backup_target="$1"
 			debug_print -e -Y -S "(${FUNCNAME[0]}) No backup destination specified."
@@ -91,25 +90,24 @@ backup_file()
 catch_exit()
 {
 	code=$?
-	debug_print -e -B -S "START DATE: $START_DATE"
-	debug_print -e -B -S "END DATE: $(date +%m-%d-%y_%H:%M:%S)"
+	debug_print -e -B -S "(${FUNCNAME[0]}) START DATE: $START_DATE"
+	debug_print -e -B -S "(${FUNCNAME[0]}) END DATE: $(date +%m-%d-%y_%H:%M:%S)"
 	debug_print -e -B -S "$0 ran for  $(( $(date +%s) - $START_TIME ))s"
 	case $code in
 			# Exit codes from https://www.tldp.org/LDP/abs/html/exitcodes.html
-		0) debug_print -e -G -S "Successful Exit: $code" ;;
-		1) debug_print -e -R -S "General Fatal Exit: $code " ;;
-		2) debug_print -e -R -S "Misuse of shell builtins: $code" ;;
-		126) debug_print -e -R -S "Command invoked cannot execute: $code" ;;
-		127) debug_print -e -R -S "Command not found: $code" ;;
-		128) debug_print -e -R -S "Invalid argument to exit: $code" ;;
-		129|13[0-9]|14[0-9]|15[0-9]|16[0-5])debug_print -e -R -S "Fatal error signal: $code" ;;
-		130) debug_print -e -Y -S "Script terminated by Control-C: $code" ;;
+		0) debug_print -e -G -S "(${FUNCNAME[0]}) Successful Exit: $code" ;;
+		1) debug_print -e -R -S "(${FUNCNAME[0]}) General Fatal Exit: $code " ;;
+		2) debug_print -e -R -S "(${FUNCNAME[0]}) Misuse of shell builtins: $code" ;;
+		126) debug_print -e -R -S "(${FUNCNAME[0]}) Command invoked cannot execute: $code" ;;
+		127) debug_print -e -R -S "(${FUNCNAME[0]}) Command not found: $code" ;;
+		128) debug_print -e -R -S "(${FUNCNAME[0]}) Invalid argument to exit: $code" ;;
+		129|13[0-9]|14[0-9]|15[0-9]|16[0-5])debug_print -e -R -S "(${FUNCNAME[0]}) Fatal error signal: $code" ;;
+		130) debug_print -e -Y -S "(${FUNCNAME[0]}) Script terminated by Control-C: $code" ;;
 			# Custom exit codes
-		100) debug_print -e -Y -S "Unspecified error: $code" ;;
-		101) debug_print -e -R -S "Missing required variable or argument: $code" ;;
-		*) debug_print -e -Y -S "Unknown exit: $code" ;;
+		100) debug_print -e -Y -S "(${FUNCNAME[0]}) Unspecified error: $code" ;;
+		101) debug_print -e -R -S "(${FUNCNAME[0]}) Missing required variable or argument: $code" ;;
 	esac
-	catch_exit_custom "$?"
+	catch_exit_custom "$code"
 	if [ $GARBAGE_COLLECTOR -eq 1 ]; then
 		for t in "${GARBAGE[@]}"
 		do
@@ -120,11 +118,12 @@ catch_exit()
 }
 check_binaries()
 {
-	debug_print -e -B -S "(${FUNCNAME[0]}) PATH=$PATH"
+	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args ($#): $*"
 	if [ $# -lt 1 ];then
-		debug_print -e -Y -S "(${FUNCNAME[0]}) No binary package list to check."
+		debug_print -e -Y -S "(${FUNCNAME[0]}) Not enough arguments received."
 		return 0
 	fi
+	debug_print -e -B -S "(${FUNCNAME[0]}) Using PATH=$PATH"
 	missing=0
 	arr=("$@")
 	debug_print -e -B -S "(${FUNCNAME[0]}) Received binary package list: ${arr[*]}"
@@ -134,7 +133,6 @@ check_binaries()
 			debug_print -e -G -S "(${FUNCNAME[0]}) Found $p"
 		else
 			debug_print -e -Y -S "(${FUNCNAME[0]}) Missing binary package: $p"
-			BINARIES_MISSING=( "${BINARIES_MISSING[@]}" "$p" )
 			((missing++))
 		fi
 	done
@@ -142,7 +140,8 @@ check_binaries()
 }
 garbage_add()
 {
-	[ $# -lt 1 ] && fail_notice_exit "(${FUNCNAME[0]}) No arguments received." 101
+	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args ($#): $*"
+	[ $# -lt 1 ] && fail_notice_exit "(${FUNCNAME[0]}) Not enough arguments received." 101
 	for a in "$@"
 	do
 		debug_print -e -B -S "(${FUNCNAME[0]}) Adding to GARBAGE pile: $a"
@@ -152,7 +151,8 @@ garbage_add()
 }
 garbage_dump()
 {
-	[ $# -lt 1 ] && fail_notice_exit "(${FUNCNAME[0]}) No arguments received." 101
+	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args ($#): $*"
+	[ $# -lt 1 ] && fail_notice_exit "(${FUNCNAME[0]}) Not enough arguments received." 101
 	for i in "$@"
 	do
 		if [ -f "$i" ];then
@@ -172,6 +172,7 @@ garbage_dump()
 }
 debug_state()
 {
+	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args ($#): $*"
 	debug_print -e -B -S "(${FUNCNAME[0]}) Current Template Variable State: "
 	debug_print -e -B -S "(${FUNCNAME[0]}) WORK_DIR: $WORK_DIR"
 	debug_print -e -B -S "(${FUNCNAME[0]}) FORCE_FLAG: $(var_state $FORCE_FLAG)"
@@ -188,26 +189,33 @@ debug_state()
 }
 fail_notice_exit()
 {
-	if [ $# -eq 0 ]; then
-		desc="Unknown"
-		error_code=100
-	elif [ $# -eq 1 ]; then
-		desc="$1"
-		error_code=100
-	elif [ $# -gt 2 ]; then
-		debug_print -e -Y "(${FUNCNAME[0]}) Received more than 2 required args: $*"
-		desc="$1"
-		error_code="$2"
-	else
-		desc="$1"
-		error_code="$2"
-	fi
+	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args ($#): $*"
+	case "$#" in
+		0)
+			desc="Unknown"
+			error_code=100
+			;;
+		1)
+			desc="$1"
+			error_code=100
+			;;
+		2)
+			desc="$1"
+			error_code="$2"
+			;;
+		*)
+			debug_print -e -Y "(${FUNCNAME[0]}) Received more than 2 required args: $*"
+			desc="$1"
+			error_code="$2"
+			;;
+	esac
 	local_print -e -R -S "Failure: $desc"
 	exit $error_code
 }
 get_response()
 {
-	[ $# -lt 1 ] && fail_notice_exit "(${FUNCNAME[0]}) Missing question argument." 101
+	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args ($#): $*"
+	[ $# -lt 1 ] && fail_notice_exit "(${FUNCNAME[0]}) Not enough arguments received." 101
 	debug_print -e -B -S "(${FUNCNAME[0]}) Received question: $1"
 	reply=""
 	[ $FORCE_FLAG -eq 1 ] && reply="y"
@@ -234,43 +242,38 @@ get_response()
 local_print()
 {
 	if [ $LOGGING -eq 1 ]; then
-		cprint -e -l "$LOG_FILE" "$@"
-		return 0
+		cprint -l "$LOG_FILE" "$@"
 	else
-		cprint -e "$@"
-		return 0
+		cprint "$@"
 	fi
 }
 debug_print()
 {
-	if [ $LOGGING -eq 1 ]; then
-		cprint -e -l "$LOG_FILE" "$@"
-		return 0
-	elif [ $DEBUG -eq 1 ]; then
-		cprint -e "$@"
-		return 0
+	if [ $LOGGING -eq 1 ] && [ $DEBUG -eq 1 ]; then
+		cprint -l "$LOG_FILE" "$@"
+	elif [ $LOGGING -eq 1 ] && [ $DEBUG -eq 0 ]; then
+		cprint -l "$LOG_FILE" "$@" >/dev/null 2>&1
+	elif [ $LOGGING -eq 0 ] && [ $DEBUG -eq 1 ]; then
+		cprint "$@"
 	fi
 }
 main()
 {
+	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args ($#): $*"
 	[ $DEBUG -eq 1 ] && VERBOSE="v"
 	[ $DEBUG -eq 0 ] && QUIET="q"
 	if [ $LOGGING -eq 1 ] && [ ! -f "$LOG_FILE" ]; then
-		touch "$LOG_FILE"
-		debug_print -e -B -S "(${FUNCNAME[0]}) Created Log File: $LOG_FILE @ $START_DATE" -l "$LOG_FILE"
+		touch "$LOG_FILE" || fail_notice_exit "(${FUNCNAME[0]}) Unable to create log file @ $LOG_FILE"
+		debug_print -e -B -S "(${FUNCNAME[0]}) Created Log File: $LOG_FILE @ $START_DATE"
 	fi
 	debug_state
 	check_binaries "${BINARIES_REQUIRED[@]}"
-	return_code=$?
-	[ $return_code -ne 0 ] && fail_notice_exit "(${FUNCNAME[0]}) Missing $return_code required binaries." 101
-	check_binaries "${BINARIES_OPTIONAL[@]}"
-	return_code=$?
-	[ $return_code -ne 0 ] && debug_print -Y -S "(${FUNCNAME[0]}) Missing $return_code optional binaries."
-	[ ${#BINARIES_MISSING[@]} -gt 0 ] && debug_print -Y -S "(${FUNCNAME[0]}) Missing the following binaries: ${BINARIES_MISSING[*]}"
+	[ $? -ne 0 ] && fail_notice_exit "(${FUNCNAME[0]}) Missing $? required binaries."
 	main_custom
 }
 parse_args()
 {
+	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args ($#): $*"
 	EXTRA_ARGS=()
 	while [ ${#} -gt 0 ]; do
 		case "${1}" in
@@ -369,10 +372,10 @@ cprint()
 		[ -z "${CPRINT_FOREGROUND}" ] && CPRINT_FOREGROUND=""
 		[ -z "${CPRINT_BACKGROUND}" ] && CPRINT_BACKGROUND=""
 		RESET=$(CPRINT_translate_color_code "RESET")
-		if [ -f "$(which printf 2>/dev/null)" ];then
+		if [ ! -f "$(which printf 2>/dev/null)" ] || [ ! -z ${USE_ECHO} ]; then
+			[ ! -z ${CPRINT_ERR_OUT} ] && (>&2 echo -n -e "$CPRINT_FOREGROUND""$CPRINT_BACKGROUND""$CPRINT_STRING""$RESET") || echo -n -e "$CPRINT_FOREGROUND""$CPRINT_BACKGROUND""$CPRINT_STRING""$RESET"
+		else
 			[ ! -z ${CPRINT_ERR_OUT} ] && (>&2 printf -- "$CPRINT_FOREGROUND$CPRINT_BACKGROUND%$CPRINT_POS"s"$RESET" "$CPRINT_STRING") || printf -- "$CPRINT_FOREGROUND$CPRINT_BACKGROUND%$CPRINT_POS"s"$RESET" "$CPRINT_STRING"
-		else # printf doesn't exist
-			[ ! -z ${CPRINT_ERR_OUT} ] && (>&2 echo "$CPRINT_FOREGROUND""$CPRINT_BACKGROUND""$CPRINT_STRING""$RESET") || echo "$CPRINT_FOREGROUND""$CPRINT_BACKGROUND""$CPRINT_STRING""$RESET"
 		fi
 		[ ! -z ${CPRINT_LOG_CPRINT_STYLED} ] && echo -e "$CPRINT_STRING" >> "$CPRINT_LOG_CPRINT_STYLED"
 	}
@@ -423,7 +426,7 @@ cprint()
 			"RESET") CODE='m' ;;
 		esac
 		case "$(uname -s)" in
-			"Darwin") echo "\033[""$CODE" ;;
+			"Darwin" | "FreeBSD") echo "\033[""$CODE" ;;
 			"Linux") echo "\e[""$CODE" ;;
 			*)
 				echo "Unknown System: $(uname -s)"
@@ -505,6 +508,7 @@ cprint()
 				"-B" | "--blue") CPRINT_FOREGROUND="$(CPRINT_translate_color_code 'FGBLUE')" ;;
 				"-C" | "--cyan") CPRINT_FOREGROUND="$(CPRINT_translate_color_code 'FGCYAN')" ;;
 				"-P" | "--purple") CPRINT_FOREGROUND="$(CPRINT_translate_color_code 'FGPURPLE')" ;;
+				"--use-echo") USE_ECHO=1 ;;
 				"-Z" | "--random") CPRINT_FOREGROUND="$(CPRINT_translate_color_code "FG$(CPRINT_random_color)")" ;;
 				"-L" | "--log-styled")
 					if [ -d "$2" ]; then
@@ -584,7 +588,7 @@ get_autopkg_trust_behavior()
 				debug_print -R -S "(${FUNCNAME[0]}) FAIL_RECIPES_WITHOUT_TRUST_INFO set to Unknown value: $R."
 				return 66
 				;;
-			esac
+		esac
 	fi
 }
 set_autopkg_trust_behavior()
@@ -611,7 +615,7 @@ set_autopkg_trust_behavior()
 	defaults $action com.github.autopkg FAIL_RECIPES_WITHOUT_TRUST_INFO $value
 	return_code=$?
 	case "$return_code" in
-		0) debug_print -G -S "(${FUNCNAME[0]}) Successful action $action to FAIL_RECIPES_WITHOUT_TRUST_INFO with value: $value";;
+		0) debug_print -G -S "(${FUNCNAME[0]}) Successful action $action to FAIL_RECIPES_WITHOUT_TRUST_INFO with value: $value" ;;
 		*) debug_print -R -S "(${FUNCNAME[0]}) Failed action $action to FAIL_RECIPES_WITHOUT_TRUST_INFO with value: $value" ;;
 	esac
 	return $return_codes
@@ -655,9 +659,9 @@ parse_args_custom()
 			"--get-trust-behavior")
 				get_autopkg_trust_behavior
 				case "$?" in
-					0) local_print -R -S "FAIL_RECIPES_WITHOUT_TRUST_INFO = FALSE";;
-					1) local_print -G -S "FAIL_RECIPES_WITHOUT_TRUST_INFO = TRUE";;
-					*) local_print -Y -S "FAIL_RECIPES_WITHOUT_TRUST_INFO = NOT SET";;
+					0) local_print -R -S "FAIL_RECIPES_WITHOUT_TRUST_INFO = FALSE" ;;
+					1) local_print -G -S "FAIL_RECIPES_WITHOUT_TRUST_INFO = TRUE" ;;
+					*) local_print -Y -S "FAIL_RECIPES_WITHOUT_TRUST_INFO = NOT SET" ;;
 				esac
 				exit 0
 				;;
